name: Auto Comment on Push to Main

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write  # Important! Permission to comment on PRs

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            🎉 Thank you for updating the files in the main branch! We appreciate your contribution! 🚀
